### ISSUE TITLE
Error when running online_planning_example_1.m

### ISSUE THREAD

**Issue by BorneWang** [ramvasudevan/RTD#1]
Hi,

When I run the example code "running online_planning_example_1.m", I got these errors:

#######################################################
Error using world_to_local
Too many input arguments.

Error in segway_RTD_planner_static/process_world_info (line 99)
                O_FRS = world_to_local(P.agent_state,O,x0,y0,D) ;

Error in generic_RTD_planner/prep_for_trajopt (line 283)
            P.process_world_info(world_info,start_tic) ;

Error in generic_RTD_planner/replan (line 246)
            P.prep_for_trajopt(agent_info,world_info,replan_start_tic)

Error in simulator/run (line 211)
                            [T_nom,U_nom,Z_nom] = P.replan(agent_info,world_info) ;

Error in online_planning_example_1 (line 23)
S.run ;
#########################################################

And I checked these functions, the input parameters are either too much or less.
Please help me figure this out.

Thanks!

**Comment by skousik** [comment]
Hi,

I've fixed the bug. Instead of calling `world_to_local` in `segway_RTD_planner_static` (line 99), it should be `world_to_FRS`

An additional bug was removing the extra input arguments on line 132 to `world_to_local`

Thanks for your help!

**Comment by skousik** [comment]
By the way, we also have new code available here: https://github.com/skvaskov/RTD

And the paper has been updated: https://arxiv.org/abs/1809.06746
